### ISSUE TITLE
Running out of memory when compiling new analyzer

### ISSUE THREAD

**Issue by nowojewski** [rsennrich/SMORLemma#2]
Hi,

I am trying to compile a new SMOR analyzer with the current Wiktionary. However, despite following the instructions (i.e. getting all the dependencies, generating XML output from Zmorge etc)  I  am getting this error:

`ulimit -d 50000000; sfst/fst-compiler-utf8-epsilonfilter morph-lemma.fst morph-lemma.a`
`morph-lemma.fst: 8`
`  symbols.fst: 80`
`morph-lemma.fst: 10`
`reading transducer from morph2.a...finished`
`morph-lemma.fst: 47`
`Allocation of memory failed in Mem::add_buffer!`
`Makefile:47: recipe for target 'morph-lemma.a' failed`
`make: *** [morph-lemma.a] Error 1`

when i adjust ulimit to less than 50GB i am simply hitting the memory problem earlier and i don't have access to instances wit more memory than that. What am i doing  wrong? I am using Ubuntu 18.04 and I installed all  the dependencies using apt-get.

The wiki-lexicon.xml that i get out of current Wiktionary is about 18MB (in case the problem lies further upstream - e.g. perhaps something compiled incorrectly?). Any help would be very appreciated.

**Comment by rsennrich** [comment]
Hi Andrzej,

I'm afraid the memory requirements may be higher than 50GB because some FST transformations can be very memory-hungry. I had access to a machine with 100GB of memory when I built the transducers; I'll see if I can find the time to build a new Transducer with the newest Wiktionary dump (in the past, QA was the most time-consuming step, since Wiktionary pages may change in a way that the extractor cannot handle).

best wishes,
Rico

**Comment by nowojewski** [comment]
Hi Rico,

Thank you for your answer - i thought i was doing something wrong. I will now try to find a bigger instance. If you get around to building a new transducer i will definitely use it.

Thanks for a great set of libraries!

Andrzej
